### ISSUE TITLE
Indenting Vendor Prefixes

### ISSUE THREAD

**Issue by dustindowell22** [postcss/sugarss#47]
This is low priority, but I'd like to indent my non-standard vendor prefixes. Do you think this should work? I remember reading somewhere about when mixing tabs/spaces that as long as it's indented _more_ it should work.

```
.foo
  -webkit-appearance: none
     -moz-appearance: none
```

```
Error: /Users/dustin/Github/plump/src/_input.sss:6:1: Expected 4 indent, but get 5
  -webkit-appearance: none
     -moz-appearance: none
^
```

**Comment by ai** [comment]
I like this vendor prefix indent in CSS too :).

But it is a different indent-based syntax. Indent is very important for SugarSS and other indent-based syntax. So I think that having special case for it will be very dangerous for SugarSS maintainability and simplicity.

Especially because with Autoprefixer we have only few cases. For example, Autoprefixer supports `appearance: none`, so even you don’t need vendor prefixes here :).

**Comment by SeanTankGarvey** [comment]
Indents need to be four spaces to be recognized, according to what I know. Just throwing that out there.
