### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by ghost** [postcss/sugarss#69]
documentation please.

**Comment by ai** [comment]
@atilkan What question do you have to open it in docs?

**Comment by atilkan** [comment]
@ai Syntax and staff.

**Comment by ai** [comment]
We have examples in our docs.

Are you try to say, that examples is not enough? What format will be better?

**Comment by atilkan** [comment]
It can be better format but i just expected more details and examples. Also searching google ends up with dead links.

**Comment by ai** [comment]
@atilkan I understand. But I can’t write good docs without your help, because I can’t understand hard parts. Can you help me?

For instance, can you make a list of the questions? Yeap, understand, that it is not easy sometimes, because to make a question, you need to understand what you want. But here you can tell me just your story. Where do you want to use SugarSS? Why do you want to use it? What are your worries about it? What do you want to make?

**Comment by atilkan** [comment]
I want to learn a bit and see if it fits my needs. Coming from Stylus and this seemed similar. Stylus not maintained so i am in search of something similar to build a library. 
For example;
Does it support file globing? 
Does it have build in functions?

**Comment by ai** [comment]
Do [Syntax → Other](https://github.com/postcss/sugarss#other) and [Usage](https://github.com/postcss/sugarss#usage) sections now answer to your questions?

**Comment by atilkan** [comment]
Nope. They don't scratch the surface.

**Comment by jt3k** [comment]
can i import json file? 
for example how it works in stylus

**Comment by ai** [comment]
@jt3k you can use `postcss-js` as an input parser to parse JSON-like structures

**Comment by flosker** [comment]
Hi, I have few questions, which docs don't seem to cover.

1. Am I supposed to add 'sugarss' in plugins list for postcss?
I did it, and I get sugarss is not a function error.

2. Or Am I supposed to add '.sss' file as a link in my html?

Basically I just couldn't get css with sugarss syntax work.

**Comment by ai** [comment]
@marceloclp please create another issue with an example
